version: "3.7"

services:
    database_locadora:
        image: postgres
        container_name: locadora
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=locadora
        volumes: 
            - pgdata:/data/postgres
            
        
    app: 
        build: .
        container_name: locadora
        restart: always
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
        
        links:
            - database_locadora
        depends_on: 
            - database_locadora

volumes: 
    pgdata:
        driver: local