version: "3.7"

services:
    database_locadora:
        image: postgres
        container_name: database_locadora
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=locadora
        volumes: 
            - pgdata:/data/postgres
        network_mode: host
    app: 
        build: .
        container_name: locadora
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
        network_mode: host

volumes: 
    pgdata:
        driver: local